export default {
  breakpoints: ["660px", "860px", "1280px", "2000px"],
  sizes: {
    mobile: "80vw",
    desktop: "85vw",
    content: 1000,
    outer: 1216,
  },
  space: [
    "0",
    "0.25em",
    "0.5em",
    "0.75em",
    "1em",
    "1.5em",
    "2em",
    "3em",
    "4em",
    "6em",
    "8em",
    "12em",
    "16em",
    "20em",
    "24em",
  ],
  fontSizes: [
    "0.844em",
    "1.125em",
    "1.5em",
    "2em",
    "2.665em",
    "3.5em",
    "4.73em",
    "6.3em",
  ],
  colors: {
    text: "#054C63",
    background: "#fff",
    primary: "#066482",
    secondary: "#D5E02D",
    muted: "#F3F3F3",
  },
  fonts: {
    body: '"Inter", Roboto, sans-serif',
    heading: '"Gilroy", Roboto, sans-serif',
    default:
      '"Inter", system-ui, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
  },
  fontWeights: {
    regular: "400",
    bold: "700",
  },
  letterSpacings: {
    heading: "0em",
    caps: "0.15em",
  },
  lineHeights: {
    body: "1.75",
    smallBody: "1.5",
    heading: "1.2",
  },
  textStyles: {
    heading: {
      fontFamily: "heading",
      fontWeight: "bold",
      lineHeight: "heading",
      overflowWrap: "break-word",
    },
    caps: {
      fontWeight: "bold",
      lineHeight: "heading",
      letterSpacing: "caps",
      textTransform: "uppercase",
      fontFamily: "heading",
    },
  },
  navigation: {
    ul: {
      padding: 0,
      margin: 0,
      listStyle: "none",
    },
    li: {
      mr: [null, null, null, 6],
      "&:last-of-type": {
        mr: 0,
      },
      a: {
        textDecoration: "none",
        color: "background",
        "&:focus-within, &:hover": {
          opacity: "0.8",
        },
      },
    },
  },
  buttons: {
    base: {
      py: [4, 5],
      px: [6, 7],
      fontSize: ["0.633em", 0],
      textDecoration: "none",
      variant: "textStyles.caps",
      cursor: "pointer",
    },
    primary: {
      variant: "buttons.base",
      bg: "rgba(255,255,255,0.15)",
      color: "#fff",
      border: "none",
      fontSize: ["0.633em", 0],
      py: 5,
      px: [5, 6],
      boxShadow: theme => `0px 2px 8px ${theme.colors.text}85`,
    },
    secondary: {
      variant: "buttons.base",
      border: theme => `3px solid ${theme.colors.secondary}`,
      bg: "transparent",
      color: "#bfca1d",
      position: "relative",

      "::before": {
        content: '""',
        display: "block",
        position: "absolute",
        top: "50%",
        transform: "translateY(-50%)",
        left: -6,
        px: [0, 5],
        bg: "#bfca1d",
        height: 3,
        transition: "transform 0.25s 0.1s",
      },
      ":hover": {
        "::before": {
          transform: "translateY(-50%) translateX(20%)",
        },
      },
    },
  },
  sections: {
    base: {
      display: "flex",
      flexDirection: "column",
      margin: "0 auto",
      width: [
        "mobile",
        "mobile",
        "mobile",
        theme => `calc(${theme.sizes.desktop} - 220px)`,
      ],
      maxWidth: "content",
      py: [8, 10, null, 11, 12],
    },
  },
  grid: {
    display: "grid",
    gridTemplateColumns: ["none", "none", "repeat(2, 1fr)"],
    gridColumnGap: [0, 0, 6, 9],
    gridRowGap: [7, 8, null, 9],
    ml: [null, null, null, "-110px"],
    mt: 4,
    mb: [6, 8, null, 9],
    width: ["100%", null, null, "calc(100% + 220px)"],
    span: {
      variant: "textStyles.caps",
      fontSize: ["0.633em", 0, null, 1],
      color: "#cccccc",
      mb: [4, 6],
      mt: [-2, -3],
      display: "block",
    },
  },
  styles: {
    Layout: {
      backgroundColor: "background",
      color: "text",
      fontFamily: "default",
      fontSize: 1,
      lineHeight: "body",
    },
    Header: {
      background:
        "linear-gradient(180deg, rgba(6, 100, 130, 0.7) 0%, rgba(15, 117, 150, 1) 100%)",
      boxShadow: "0px 3px 4px rgba(4, 77, 101, 0.25)",
      zIndex: 2,
      color: "background",
      fontWeight: "bold",
      pt: [5, null, 6],
      pb: [5, null, 6],
      variant: "navigation",
    },
    Main: {},
    Footer: {
      bg: "primary",
      color: "background",
      fontWeight: "bold",
      py: [8, 9, null, 10, 11],
      variant: "navigation",
    },
    h1: {
      variant: "textStyles.heading",
      fontSize: [4, 5, 6, 7],
      mb: 3,
    },
    h2: {
      variant: "textStyles.caps",
      color: "secondary",
      position: "relative",
      fontSize: [1, 2, 2, 3],
      mb: [4, 5, 5, 6],
      ml: [0, 7, 7, 0],
      "::before": {
        content: '""',
        display: "block",
        position: "absolute",
        top: "50%",
        transform: "translateY(-50%)",
        left: [0, -7],
        px: [0, 4],
        bg: "secondary",
        height: 4,
      },
    },
    h3: {
      variant: "textStyles.heading",
      fontSize: [1, 2, null, 3],
      mb: [2, 3],
    },
    p: {
      fontSize: [1, 2, null, 3],
      mb: 4,
      "&:last-child": {
        mb: 0,
      },
      "&:not(:last-child):last-of-type": {
        mb: [5, 6, null, 7],
      },
    },
    ul: {
      pl: 4,
    },
    li: {
      fontSize: [null, 2, null, 3],
      pl: 2,
      mb: 2,
      "&:last-of-type": {
        mb: 0,
      },
    },
  },
}
